# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "base"
	
  config.vm.define :db do |db_config|
   	
    	db_config.vm.boot_mode = :gui
    	db_config.vm.network :hostonly, "33.33.33.11"
    	db_config.vm.host_name = "dbserver"
	
	db_config.vm.provision :puppet do |puppet|
    		puppet.manifests_path = "manifests"
    		puppet.manifest_file = "dbserver.pp"
  	end

  end
end
